language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>=AKIA2WXR4NAIT3XRBFNK"
  secret_access_key:
    secure: "Encypted <secret-access-key>=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"
  region: "us-east-1"
  app: "polls"
  env: "django_tutorial_1"
  bucket_name: "the-target-S3-bucket"